### ISSUE TITLE
Unsplash have an API

### ISSUE THREAD

**Issue by braksator** [mkzero/unsplash-download#6]
Just fyi :P https://unsplash.com/developers

**Comment by mkzero** [comment]
Well, that's new. But basically this downloader would probably break 2 or 3 of their 4 terms of use. So, as much as I'd like to migrate this to a proper API, I respect their decision for those terms and don't want any trouble with the unsplash people.

To make it short: Unless someone is willing to talk to them about this, I'm closing this.
